### ISSUE TITLE
Replace tidyverse dependencies with specific components

### ISSUE THREAD

**Issue by davidski** [business-science/tidyquant#108]
Thanks for all the work on this package!

Currently, tidyquant pulls in the entire `tidyverse` meta-package, which is discouraged for package developers (reference https://www.tidyverse.org/articles/2018/06/tidyverse-not-for-packages/). To keep code leveraging tidyquant as lean as practical, could this dependency be replaced with the specific subset that are hard required for tidyquant? Thanks again!

**Comment by mdancho84** [comment]
I agree - I will look into this soon.

**Comment by mdancho84** [comment]
Done in `tidyquant` version 0.5.7.
