### ISSUE TITLE
Development `tibble` might cause issues

### ISSUE THREAD

**Issue by DavisVaughan** [business-science/tidyquant#110]
I'm 99% sure that the development version of `tibble` is going to cause some breaking changes in `tidyquant`. This is related to the fact that `tibble` is going to support matrices as columns of a tibble (and by extension, `zoo` objects).

See the `New features` here:
https://github.com/tidyverse/tibble/blob/master/NEWS.md

With the dev version of `tibble`, `tq_get()` (and `tq_mutate()`) return columns that are `zoo` objects:

```r
> tq_get("AAPL")
# A tibble: 2,701 x 7
   date       open      high      low       close     volume    adjusted 
   <date>     <S3: zoo> <S3: zoo> <S3: zoo> <S3: zoo> <S3: zoo> <S3: zoo>
 1 2008-01-02 28.46714  28.60857  27.50714  27.83429  269794700 24.66830 
 2 2008-01-03 27.91571  28.19857  27.52714  27.84714  210516600 24.67969 
 3 2008-01-04 27.35000  27.57143  25.55571  25.72143  363958000 22.79577 
```

as opposed to the cran version of `tibble` which returns `dbl` objects:

```r
> tq_get("AAPL")
# A tibble: 2,701 x 7
   date        open  high   low close    volume adjusted
   <date>     <dbl> <dbl> <dbl> <dbl>     <dbl>    <dbl>
 1 2008-01-02  28.5  28.6  27.5  27.8 269794700     24.7
 2 2008-01-03  27.9  28.2  27.5  27.8 210516600     24.7
 3 2008-01-04  27.4  27.6  25.6  25.7 363958000     22.8
```

I am guessing that `tidyquant` was relying on an implicit coercion of these objects to `double` by `tibble`, and now that is not happening. It will have to be done manually to ensure the right thing is returned. Probably somewhere in `tq_get()`, before returning a result, we could add a `mutate_if(data, is.zoo, as.numeric)`. That would be a quick patch. A better way may be to do it at a lower level right when we get the zoo object back. Same with `tq_transmute.tbl_df`

**Comment by mdancho84** [comment]
Thanks for the heads up. I'll take a look. It seems that the `zoo` piece may affect `timetk` as well and other packages relying on the implicit coercion strategy.

**Comment by mdancho84** [comment]
It seems like this is OK.
