### ISSUE TITLE
Error occurs when retrieving key ratios from a list of unique companies 

### ISSUE THREAD

**Issue by ksun91** [business-science/tidyquant#111]
Hello,

I have a list of unique companies symbols (around 1154), all listed on the US exchange.
When I try to retrieve the key ratios of each individual companies within a for loop, I get an error. The tq_get function returns NA.

However, if I wait for a little while and manually put in the stock name that caused the error into the tq_get function, then the function works (however, if I immediately put the stock name in the function right after the error, the same error occurs). Here is a script to reproduce the error:

```
stock.list = c("VNET", "TWOU", "JOBS", "ACAD", "XLRN", "ADBE", "AEIS", "AERI", "AVAV", "AGIO", "AKAM", "ALDR",
"ALXN", "ALGN", "ALKS", "ALGT", "ARLP", "ALNY", "GOOG", "AIMC")

for(s in stock.list){
  df.key.ratios <- tq_get(s,get = "key.ratios")
  
  for(i in 1:6){
    temp.df = df.key.ratios$data[[i]]
  }
}

```

> Error: $ operator is invalid for atomic vectors
> In addition: Warning messages:
> 1: In doTryCatch(return(expr), name, parentenv, handler) :
>   Units of Key Ratios Not Compatible for Valuation Ratios.
>                     Returning key ratios without Valuation Ratios.
> 2: In doTryCatch(return(expr), name, parentenv, handler) :
>   Units of Key Ratios Not Compatible for Valuation Ratios.
>                     Returning key ratios without Valuation Ratios.
> 3: x = 'AGIO', get = 'key.ratios': Error in UseMethod("as_list"): no applicable method for 'as_list' applied to an object of class "NULL"
>  
> 4: x = 'AGIO', get = 'key.ratios': Error in eval(lhs, parent, parent): object 'key_ratios_bind' not found

**Comment by mdancho84** [comment]
Unfortuntately Key Ratios no longer works - I am looking into a solution in Issue #125
