### ISSUE TITLE
after upgraded the GGPlot2 to the latest version, geom_candlestick not displaying High/Low Value bar

### ISSUE THREAD

**Issue by MSBICOE** [business-science/tidyquant#112]
It was all good for the geom_candlestick chart. However, since ggplot2 is updated to the latest version, the candlestick chart is no longer displaying the thin High/Low bar while the open/close is still OK. the warning message says: colour_up and colour_down is not mapped? my another computer with ggplot2 version < 3.0 installed still display correctly. has anybody else got the same issue? Thanks!

**Comment by optisizer** [comment]
I have similar issues, for both charts. The Bar Chart doesn't show anything. Warning message begins with: Warning: Ignoring unknown parameters: colour_up, colour_down. Then second continues with: Evaluation error: argument "color_up" is missing, with no default.
I notice a difference in spelling, british colour vs. american color.
I also notice OP posted 13 days ago and still no comment or help. That's bad and makes me wonder whether I should just ignore this package and revert back to quantmod.

**Comment by TimmyAA** [comment]
I had same problem with a new R install.
Uninstalling ggplot2 3.1.0 and installing ggplot2_2.2.1.tar.gz does work around these errors.

**Comment by MSBICOE** [comment]
Hi @optisizer & @TimmyAA, Thanks both. Good to know that this not my own problem. Why I raised this issue, just want to help in the new release this can be taken care of. As I mentioned that my another machine with older ggplot2 does work. But I hope this can be fixed asap. Thanks.

**Comment by pverspeelt** [comment]
Breaking change in ggplot2 3.1.0. All internal uses of color are automatically renamed to colour. In this instance it breaks the geom_barchart and geom_candlechart as you now have the stat functions looking for color_xx and ggplot2::layer has renamed the parameters to colour_xx. 

Simple solution is to rename everything from American color to British colour. 

See [news](https://cran.r-project.org/web/packages/ggplot2/news/news.html) of ggplot2 release:

**ggplot2 3.1.0
Breaking changes**

In non-user-facing internal code (specifically in the aes() function and in the aesthetics argument of scale functions), ggplot2 now always uses the British spelling for aesthetics containing the word “colour”. When users specify a “color” aesthetic it is automatically renamed to “colour”. This renaming is also applied to non-standard aesthetics that contain the word “color”. For example, “point_color” is renamed to “point_colour”. This convention makes it easier to support both British and American spelling for novel, non-standard aesthetics, but it may require some adjustment for packages that have previously introduced non-standard color aesthetics using American spelling.

**Comment by YourEconProf** [comment]
My solution (aargh.)

> library(devtools)
> install_version("ggplot2",version = "3.0.0")

**Comment by randalleclayton** [comment]
I have a change to geom_chart.R code to fix this issue. While I have software development and R experience, I have not previously submitted a pull request to tidyquant. If I submit a pull request, is it likely someone will look at it and consider merging my fix? 

In my fix, any existing code using geom_candlestick or geom_barchart will have to change the color_up and color_down arguments to colour_up and color_down to bring naming in alignment with ggplot2 (I could have just fixed the code to use colour_up and colour_down internally, but that seems against the spirit of the ggplot2 changes).

**Comment by andremueller** [comment]
Finally I found this issue here - after fumbling around for many hours. I find it really difficult to debug such issues within ggplot2. Regarding ggplot: Is it probably a bad idea to automatically rename such American to British spelling (I know - this question should be put to the ggplot group, too). Why should an API do such weird things as renaming all parameters? Only because the R language supports such features it may be questionable to make use of that specific feature - accepting the consequence of just breaking other packages.

**Comment by robachmann** [comment]
@mdancho84 is there a solution in sight? The problem already exists for 9 months and currently the library does not work properly.

**Comment by mdancho84** [comment]
@robachmann Currently it's just me working on this. I know 9 months seems like a long time, but I am building a startup. I continue to keep tidyquant moving forward, but growing my company is taking precedence at the moment. The color bars are a minor feature. Thanks for your consideration of priorities.

**Comment by robachmann** [comment]
Thanks for your quick response. Giving such insights makes it understandable. Although it is a minor feature, I believe it makes it impossible to plot such candlebar-plots at the moment. However, it's an open-source project and you invite others to assist you. I think @andremueller has thankfully added a PR for this but it would still need to be merged and released.

Anyway, as a newcomer I was surprised the tutorials don't work out of the box anymore. I found  [plot.ly](https://plot.ly/r/candlestick-charts/) to be quite helpful for my case and can recommend it to people who are looking for this feature _right now_.

All the best and good luck with your startup :four_leaf_clover:

**Comment by mdancho84** [comment]
This should be fixed now.
