### ISSUE TITLE
Compatibility with 'import' package?

### ISSUE THREAD

**Issue by kaybenleroll** [business-science/tidyquant#116]
I have started to use the 'import' package as it helps a lot with namespace clashes and so on.

https://cran.r-project.org/web/packages/import/index.html

Unfortunately, when trying to use `tq_transmute()` this throws the following error:

> Error in as.environment(pos) : 
>  no item called "package:zoo" on the search list
 
I think this is happening because of the use of the function `tq_transmute_fun_options` which calls `ls()` on the various packages. I'm happy to help out on any fixes as I really like how clean `import` is and I expect to be using tidyquant quite a bit, and would rather not have to explicitly make those `library()` calls if I don't have to.

Thanks for all your work on `tidyquant` - it is a fantastic package!

**Comment by jjfantini** [comment]
Have you made any progress or  found a solution to this error? @kaybenleroll

**Comment by fernando-duarte** [comment]
+1 on fixing this issue, just run into it today

**Comment by fernando-duarte** [comment]
Thank you!
