### ISSUE TITLE
tq_index does not work

### ISSUE THREAD

**Issue by waynelapierre** [business-science/tidyquant#119]
The tq_index function does not work and the error message states that I need to load the package XLConnect package. I think this issue is due to rJava.

**Comment by mdancho84** [comment]
Yeah, I'm getting this too. I'm looking into.

**Comment by mdancho84** [comment]
For the time being you can use the argument `use_fallback = TRUE`. The index is a bit dated, but should still be close.

**Comment by mdancho84** [comment]
I found a fix in this [GitHub Issue](https://github.com/rstudio/rstudio/issues/2254)

Go to your terminal and run this:

```
sudo R CMD javareconf
```

Then close and reopen RStudio IDE. You should be good to go.

**Comment by mdancho84** [comment]
We removed dependencies to rJava in v0.5.6. This should be corrected now.
