### ISSUE TITLE
geom_barchart not working

### ISSUE THREAD

**Issue by tht18** [business-science/tidyquant#126]
It is not even working with the help example:

AAPL <- tq_get("AAPL", get = "stock.prices", from = "2000-01-01", to = "2018-12-31")

AAPL %>%
+     ggplot(aes(x = date, y = close)) +
+     geom_barchart(aes(open = open, high = high, low = low, close = close))+ 
+     labs(title = "AAPL Bar Chart", y = "Closing Price", x = "")+ 
+     theme_tq()

Warning: Ignoring unknown parameters: colour_up, colour_down
Warning: Ignoring unknown parameters: colour_up, colour_down
Warning: Ignoring unknown parameters: colour_up, colour_down
Warning messages:
1: Computation failed in `stat_linerange_bc()`:
Evaluation error: argument "color_up" is missing, with no default. 
2: Computation failed in `stat_segment_left_bc()`:
Evaluation error: argument "color_up" is missing, with no default. 
3: Computation failed in `stat_segment_right_bc()`:
Evaluation error: argument "color_up" is missing, with no default.

**Comment by YourEconProf** [comment]
This is partially at least the same as https://github.com/business-science/tidyquant/issues/112 The solution is to downgrade ggplot2 to 3.0.0 or avoid using the tidyquant graphics routines.

**Comment by mdancho84** [comment]
This should be fixed now in the development version of tidyquant. We will release v0.5.7 to CRAN shortly.
