### ISSUE TITLE
tq_get key.ratios does not work

### ISSUE THREAD

**Issue by Razed850** [business-science/tidyquant#127]
Running the following code gives me: 

> tq_get("AAPL",get = "key.ratios")
[1] NA
Warning messages:
1: x = 'AAPL', get = 'key.ratios': Error in UseMethod("as_list"): no applicable method for 'as_list' applied to an object of class "NULL"
 
2: x = 'AAPL', get = 'key.ratios': Error in eval(lhs, parent, parent): object 'key_ratios_bind' not found

I've tried to install the dev tools version of tidyquant as indicated by former issues without success.

**Comment by mdancho84** [comment]
Unfortunately, Morningstar has changed their website to make retreiving key ratios very difficult. We had to deprecate this functionality in tidyquant v0.5.6.
