### ISSUE TITLE
tq_exchange problem

### ISSUE THREAD

**Issue by eweiss99** [business-science/tidyquant#138]
Sometime in the last few days, nasdaq moved (deleted?) their listing for stock symbols and names and I can't find a new copy.

Example: 

library(tidyquant)
tq_exchange("nyse")

In download.file(url, destfile = tmp, quiet = TRUE) :
  cannot open URL 'https://www.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=nyse&render=download': HTTP status was '404 Not Found'

**Comment by mdancho84** [comment]
This should be fixed now.

**Comment by model7** [comment]
This might be happening again.  I'm getting a similar error when running tq_exchange() using AMEX, NASDAQ, and NYSE.

**Comment by mdancho84** [comment]
@model7 Make sure you use the latest version - `tidyquant` v0.5.8

**Comment by model7** [comment]
Thanks @mdancho84. My mistake. I'm using that version, but had a VPN running. Turned off the VPN and it worked.

**Comment by mdancho84** [comment]
Sounds good. Thanks for the heads up.
