### ISSUE TITLE
HTTP 404 ERROR WHEN USING TIDYQUANT

### ISSUE THREAD

**Issue by anagarza331** [business-science/tidyquant#143]
Hi, im having trouble running this chunk of code. I did run it this morning and worked perfectly. 

rm(list = ls()) 

library(tidyquant)
library(ggplot2)
library(quadprog)
library(reshape2)
list_stonks<- c("^MXX", "GRUMAB.MX", "ASURB.MX", "AMXL.MX", "ALSEA.MX", "GCARSOA1.MX", "ALPEKA.MX",
                "AC.MX", "PINFRA.MX", "GCC.MX", "BSMXB.MX", "TLEVISACPO.MX", "BIMBOA.MX", "GAPB.MX",
                "BBAJIOO.MX", "GMEXICOB.MX","RA.MX","LABB.MX", "GENTERA.MX", "CEMEXCPO.MX",
                "GFNORTEO.MX", "OMAB.MX", "KIMBERA.MX", "MEXCHEM.MX", "CUERVO.MX", "BOLSAA.MX",
                "MEGACPO.MX", "LIVEPOLC1.MX", "KOFL.MX", "IENOVA.MX", "PEOLES.MX")

stock_returns_monthly <- c(list_stonks) %>%
  tq_get(get = "stock.prices",
         from = "2011-01-03",
         to = "2019-02-03") %>%
  group_by(symbol) %>%
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = "monthly",
               col_rename = "Ra")
stock_returns_monthly

Does anyone know if this is a yahoo finance problem?
thanks

**Comment by mdancho84** [comment]
I just ran `tidyquant::tq_get("AAPL")` and it worked fine. Make sure you have an internet connection, otherwise you will get an error.
