### ISSUE TITLE
tq_index() - No longer works for SP500 and others

### ISSUE THREAD

**Issue by mdancho84** [business-science/tidyquant#144]
The function `tq_index()` is resulting in an error when downloading market indexes. 

```
> tq_index("SP500")
Getting holdings for SP500
# A tibble: 0 x 0
Warning message:
In tq_index("SP500") : Error at SP500 during download. 
Error: 
  filepath: /private/var/folders/st/s5vwv9pd27g7z2sffwlqmtv80000gn/T/RtmpRZR2kL/file21386a287ba1.xls
  libxls error: Unable to open file
```

**Comment by mdancho84** [comment]
Issue is fixed in `tidyquant` v0.5.9. Submitting to CRAN today. Should be on CRAN shortly.

**Comment by zac-garland** [comment]
Thanks @mdancho84! I downloaded the dev version and it looks like it's working. Appreciate the quick turnaround!

**Comment by mdancho84** [comment]
You got it Zac.
