### ISSUE TITLE
While loading packages it is giving error

### ISSUE THREAD

**Issue by ahmedkhancgt** [business-science/tidyquant#145]
Error: package or namespace load failed for ‘tidyquant’:
 .onAttach failed in attachNamespace() for 'tidyquant', details:
  call: if (theme$dark) {
  error: missing value where TRUE/FALSE needed
In addition: Warning messages:
1: package ‘tidyquant’ was built under R version 3.5.3 
2: package ‘PerformanceAnalytics’ was built under R version 3.5.3

**Comment by mdancho84** [comment]
Hi Ahmed,
What does this command return?
```
rstudioapi::getThemeInfo()
```

**Comment by ahmedkhancgt** [comment]
$`editor`
NULL

$global
[1] "Modern"

$dark
[1] NA

**Comment by ahmedkhancgt** [comment]
Thanks, Matt for help I resolved the issue by selecting the default theme text mate
