### ISSUE TITLE
Applying "rollify" to "allReturns" function

### ISSUE THREAD

**Issue by ecitera** [business-science/tidyquant#149]
Hi,

I would like to compute returns for different holding periods,  just like the "allReturns" function does, but for every single day of my dataset. This means that, in the case of weekly returns, I want to have them for every single day (and not just at the end of each week), by lagging every daily observation by a week.

I found out that the "rollify" function actually does almost what I want. Here's my code:
`my_data <- tq_get('^GSPC', from = '1962-01-01', to = '2020-01-01')`
`Log_ret <- my data %>% select(close, date) %>% tq_transmute(select = close, mutate_fun = allReturns, type = 'log', leading = F)`
`week_ret <- rollify(sum, window = 5)`
`Log_ret <- Log_ret %>% mutate(Yweekly2 = week_ret(daily))`

The issue is that not all weeks have the same length (some of them have only 4 trading days). To sort this issue I tried to do this `rollify <- (sum, window = diff(endpoints(my_data$date, 'weeks')))`
but I get the following error: `"Error: assert_that: length of assertion is not 1"`.

Do you know if is there a way to pass a function to the argument "window"? If not, do you have any suggestions on how to get around this issue?

Thanks a lot for your help, I really appreciate.

Emanuele

**Comment by DavisVaughan** [comment]
You should look into `slide_index()` from {slider} https://davisvaughan.github.io/slider/articles/slider.html

It's way better than `rollify()` (I wrote both)

**Comment by ecitera** [comment]
Thank you, I actually discovered this function the other day and it really saved my life! Congratulations, that's extremely useful!! 💯
