### ISSUE TITLE
When trying to load the tidyquant package in RStudio-1.1.463

### ISSUE THREAD

**Issue by wirapong** [business-science/tidyquant#152]
When trying to load the tidyquant package in RStudio-1.1.463, I get the following error message:

Error: package or namespace load failed for ‘tidyquant’:
 .onAttach failed in attachNamespace() for 'tidyquant', details:
  call: if (theme$dark) {
  error: missing value where TRUE/FALSE needed
I do not use the latest version because it is not compatible with my 32-bit machine. I did not have that issue while I was using the latest RStudio version so I suppose that causes the issue. Any workaround for this version?

**Comment by mdancho84** [comment]
Hi this should be fixed with #157 . Use the development version of tidyquant until the next CRAN release. `devtools::install_github("business-science/tidyquant")`
