### ISSUE TITLE
Issue with "weight" in "tq_index()"

### ISSUE THREAD

**Issue by ecitera** [business-science/tidyquant#153]
Hi guys, I'm having the following problem.

If I run the code `SP500 <- tq_index('SP500')`, why the variable "weight" reports different values than those available at the following link (https://www.ssga.com/us/en/institutional/etfs/library-content/products/fund-data/etfs/us/holdings-daily-us-en-spy.xlsx), which I retrieved from the call of the original function, available here (https://github.com/business-science/tidyquant/commit/5cabd7737ed92cc01d56a1e710229ab979a9a63f#comments), at line 242:

`spdr_link <- paste0("https://www.ssga.com/us/en/institutional/etfs/library-content/products/fund-data/etfs/us/holdings-daily-us-en-", tolower(x), ".xlsx")`

Thanks a lot for your help, I really appreciate

**Comment by mdancho84** [comment]
We re-weight because SPY is an ETF and has some funds in cash. We remove this cash line item called Sector = "Unassigned" and re-weight to estimate the approximate asset weights.

**Comment by ecitera** [comment]
Thanks a lot @mdancho84 , this is very helpful. Actually the weights are very close to the actual ones, so this shouldn't be a problem. I was just wondering why they were different...
