### ISSUE TITLE
Update windows binary to 1.0.0

### ISSUE THREAD

**Issue by Fredo-XVII** [business-science/tidyquant#156]
Hello Matt,

I just downloaded tidyquant from CRAN and I received v0.5.10 instead of v1.0.0.  I noticed that the CRAN page still has the old version for the windows binary.

Windows binaries: | r-devel: tidyquant_0.5.10.zip,

Can you update the windows binary?

thanks

**Comment by mdancho84** [comment]
Hi @Fredo-XVII ,
CRAN will update all of the binaries soon. In the meantime, you can get tidyquant 1.0.0 installed via `devtools::install_github("business-science/tidyquant")`.
-Matt

**Comment by Fredo-XVII** [comment]
Ok, thank you for the quick response!

**Comment by mdancho84** [comment]
This issue should be fixed now.
