### ISSUE TITLE
Cant load package

### ISSUE THREAD

**Issue by gonzalorondinone** [business-science/tidyquant#157]
Dear all, 

When I tried to load the package I get this

Error: package or namespace load failed for ‘tidyquant’:
 .onAttach failed in attachNamespace() for 'tidyquant', details:
  call: NULL
  error: Function getThemeInfo not found in RStudio

rstudioapi is installed and latest RStudio version

**Comment by mdancho84** [comment]
Try loading the development version with: `devtools::install_github("business-science/tidyquant")`
