### ISSUE TITLE
pivot_table() error - argument "expr" is missing, with no default

### ISSUE THREAD

**Issue by sanjiv777** [business-science/tidyquant#158]
Hi Matt,

I get an error message when I run the pivot_table script in Lab30 (Section 3.1), within the 02_pivot_tables.R file:

stock_data_tbl %>% 
    pivot_table(
        .values  = ~ MEDIAN(volume)
        )

Error in is_call(expr, paren_sym) : 
  argument "expr" is missing, with no default

I've updated all related packages including rlang and dplyr as sugested, but still no luck. Any other suggestions?

**Comment by mdancho84** [comment]
Try using the development version: `devtools::install_github("business-science/tidyquant")`. While I troubleshoot, this will make sure we are using the same version.

**Comment by mdancho84** [comment]
Try this in a new / fresh R session:

```
library(tidyverse)
library(tidyquant)

FANG %>%
    pivot_table(
        .values = ~ MEDIAN(volume)
    )
```

I expect you will get the same issue.

**Comment by sanjiv777** [comment]
> Try using the development version: `devtools::install_github("business-science/tidyquant")`. While I troubleshoot, this will make sure we are using the same version.

When I ran the development version twice, I had these errors (exclusively) each time:

**1st error:**
In tq_index("SP500") : Error at SP500 during download. 
Error in utils::packageVersion("curl"): there is no package called ‘curl’

**2nd error:**
In find.package(if (is.null(package)) loadedNamespaces() else package,  :
  there is no package called ‘fansi’

installing and loading these packages sorted it out

**Comment by mdancho84** [comment]
OK great. I also heard from a student that updating packages solved the issue. Since he updated so many, it wasn't clear which package needed the update to fix the issue. I'm closing this issue out.

**Comment by sanjiv777** [comment]
> Try this in a new / fresh R session:
> 
> ```
> library(tidyverse)
> library(tidyquant)
> 
> FANG %>%
>     pivot_table(
>         .values = ~ MEDIAN(volume)
>     )
> ```
> 
> I expect you will get the same issue but this will help me make a reproducible example.

I could run the code without any error after running the development version the first time + installing curl.

**Comment by mdancho84** [comment]
Perfect!

**Comment by sanjiv777** [comment]
Thank you! Love your work, Matt!

**Comment by mdancho84** [comment]
Thanks for helping to resolve the issue. Keep it up.

**Comment by Financebro1** [comment]
Hey, when i try to use any command all i get is this error:'cli_h1' is not an exported object from 'namespace:cli'

Am i doing something wrong, or is this a quick fix?
