### ISSUE TITLE
feature: convenient way to change all prices to a defined basis currency

### ISSUE THREAD

**Issue by robby81** [business-science/tidyquant#16]
Hi mdancho84,

I just started working with tidyquant mainly to analyze my own portfolio of ETFs. I wondered whether there is a simple method to convert all prices to a defined currency? Would be probably a nice feature for tidyquant, if there is not an easy way to do that.

Cheers,
Robby.

**Comment by mdancho84** [comment]
@robby81 
Just a heads up that we are currently gearing up for release v0.4.0 so it may take a little bit to get back to you. In the meantime, just know that we see these and will work on them as soon as possible.
Thanks, Matt

**Comment by robby81** [comment]
That's all fine. I just started using tidyquant to make some analysis on my own etf-based portfolio. And thought it is good to collect stuff, I come up with during that. :-)

**Comment by mdancho84** [comment]
I might be able to make a function for this using the oanda data. I need to investigate further. Will mark as a feature request.
