### ISSUE TITLE
Using Tidyquant "pivot_table" function i am getting an error :

### ISSUE THREAD

**Issue by mohitshrestha** [business-science/tidyquant#162]
When i am using Tidyquant "pivot_table" function i am getting an error :
Error in is_call(expr, paren_sym) : argument "expr" is missing, with no default

Link shows the code and error shown. Can you tell how to fix it?
https://pastebin.com/e6UQ3K9g

**Comment by mdancho84** [comment]
This looks like a duplicate of issue number #158 . Try following the solution and see if it works.

**Comment by mohitshrestha** [comment]
Thanks mdancho84. It worked now!

As per your suggestion, I used the development version: devtools::install_github("business-science/tidyquant").
And also updated all my R packages.

**Comment by mohitshrestha** [comment]
> This looks like a duplicate of issue number #158 . Try following the solution and see if it works.

Thanks mdancho84. It worked now!

As per your suggestion, I used the development version: devtools::install_github("business-science/tidyquant").
And also updated all my R packages.
