### ISSUE TITLE
feature: get holdings of ETFs

### ISSUE THREAD

**Issue by robby81** [business-science/tidyquant#17]
Currently I am trying to figure out, how to automatically get the holdings of all all ETFs in my portfolio to analyze which stocks, countries and sectors proportions my hole portfolio actually has.
Do you know of an way to do that? From e.g. ishares I tried to get a csv, but it is not that easy as I thought.
Would also be a nice feature for tidyquant..

Cheers,
Robby.

**Comment by mdancho84** [comment]
I know RViews recently did a post on this: [Reproducible Finance with R: ETF Country Exposure](https://www.rstudio.com/rviews/2017/02/08/reproducible-finance-with-r-etf-country-exposure/)

I'll add this as a feature request. Upon inspection adding BlackRock iShares fund data can be done.
