### ISSUE TITLE
Can't resolve host: fred.stlouisfed.org

### ISSUE THREAD

**Issue by bjhighfill** [business-science/tidyquant#179]
Hey Matt,

I'm running into issues when using tq_get(get = "economic.data").

```
ProxyConnect <- function(DSID=Sys.info()[7],Password) {
  if(!is_inst('httr')){InstallPackages('httr')}
  httr::set_config(httr::use_proxy(url="proxy.com",port=port,username=DSID,password=Password))
}

ProxyConnect(DSID=user, Password=pw)

opts <- list(
  proxy         = "proxy.com",
  proxyusername = "user",
  proxypassword = pw,
  proxyport     = port
)

fred <- tq_get(c("UNRATE"),
               get="economic.data",
               from="1990-01-01", 
               complete_cases=TRUE,
               curl.options=opts)
Warning message:
x = 'UNRATE', get = 'economic.data': Error in getSymbols.FRED(Symbols = "UNRATE", env = <environment>, verbose = FALSE, : 
Unable to import “UNRATE”. Could not resolve host: fred.stlouisfed.org
```

Passing the curl.options=opts shown above works for tq_get(get="stock.prices") and several other data pulls. Is there something I'm missing to get past the firewall or an issue with the tq_get() statement? 

Thanks in advance!

**Comment by mdancho84** [comment]
Just tried and UNRATE seems to work. Let me know if this continues. 

```
library(tidyquant)
tq_get("UNRATE", get = "economic.data")
```

**Comment by bjhighfill** [comment]
I believe the issue only arises behind a proxy server. I had to roll back the quantmod and tidyquant packages in order for the above curl.options to work with the proxy server. My assumption is that it's an issue with the new version of quantmod's ingestion of the curl.options. 

At this point, seems more of a quantmod issue rather than tq. Appreciate your help, Matt.
