### ISSUE TITLE
tq_mutate col_rename is not working

### ISSUE THREAD

**Issue by JoeFernando** [business-science/tidyquant#181]
Consider the following example:

tq_get("AAPL") %>% 
  tq_mutate(select = high,
            mutate_fun = rollapply, 
            width = 10,
            FUN = max,
            na.rm = TRUE,
            col_rename = "high_10b_high") %>% 
  tail(20)

The new column name shows-up as `rollapply` instead of `high_10b_high`

I'm using the latest version:
[1] tidyquant_1.0.1.9000 

How do I get `col_rename` to work

**Comment by IanWorthington** [comment]
I get this too with BBands.  Is fine with MACD.  Probably have to use rename()?
