### ISSUE TITLE
tq_index("SP500")

### ISSUE THREAD

**Issue by BeachGuy007** [business-science/tidyquant#195]
when I execute tq_index("SP500") it just returns the top 10 and says "# ... with 495 more rows". How can I output all the rows? Thanks

**Comment by mdancho84** [comment]
This is simply how the dataframe (tibble) prints. 
![image](https://user-images.githubusercontent.com/13734662/109360289-ed5fda00-7854-11eb-91fe-dd67c09eb6b0.png)

If you store the data as an object. You can then view it all. 

```
sp_500_tbl <- tidyquant::tq_index("SP500")

View(sp_500_tbl)
```

**Comment by BeachGuy007** [comment]
Awesome, thanks!

**Comment by BeachGuy007** [comment]
Awesome, thanks! Do you know how I can print the whole thing to a file. I tried...

sink(file)
print(sp_500_tbl)
sink()
