### ISSUE TITLE
could not find function "summarize_by_time"

### ISSUE THREAD

**Issue by NorthernHarrier** [business-science/tidyquant#196]
Using examples from https://university.business-science.io/courses  Lab 30

I get error: could not find function "summarize_by_time"

Using version 1.0.2

**Comment by mdancho84** [comment]
This function has been relocated to `timetk`. https://business-science.github.io/timetk/reference/summarise_by_time.html

**Comment by mdancho84** [comment]
Just `library(timetk)` and it should work.
