### ISSUE TITLE
tq_get suddenly not working

### ISSUE THREAD

**Issue by daexto** [business-science/tidyquant#205]
Hi . . . I've been using tq_get() for a while now to pull up stock prices and it's always worked well. Suddenly today it no longer seems to work for any of the stocks I've tried. Below is a simple example of code that worked until yesterday but now just gives a warning and NA output. This is the same whichever stock I try.

library(tidyquant)

today <- today()
test <- tq_get("AAPL", get = "stock.prices", from = today)

Warning message:
x = 'AAPL', get = 'stock.prices': Error in getSymbols.yahoo(Symbols = "AAPL", env = <environment>, verbose = FALSE, : Unable to import “AAPL”.
argument "conn" is missing, with no default

Hoping someone has an idea what might be going wrong.

Cheers

**Comment by mdancho84** [comment]
This function depends on your internet connection so anything that could interfere is likely what's happened.

**Comment by daexto** [comment]
Thanks for the super quick reply - I'll try again tomorrow and hope the connection has improved!

**Comment by mandarpriya** [comment]
Sir, today the tq_get() was not workign for me, even the quantmod did not work. Like my internet is working.

**Comment by mdancho84** [comment]
Please update your R packages.

**Comment by cemal95** [comment]
I am currently also experiencing this
