### ISSUE TITLE
Is tq_get() down from tidyquant? 

### ISSUE THREAD

**Issue by mlozanoqf** [business-science/tidyquant#216]
Hello. The following code:
`aapl_prices  <- tq_get("AAPL", get = "stock.prices", from = " 1990-01-01")`
`aapl_prices`

Leads to:
`“Warning message:
“x = 'AAPL', get = 'stock.prices': Error in new.session(): Could not establish session after 5 attempts.”`
`<NA>`

The `quantmod` package has a similar issue, but I guess the solution proposed by Joshua Ulrich does not apply for `tidyquant`.

Regards.

**Comment by bradSchrage** [comment]
@mdancho84  This is an issue with quantmod that Josh Ulrich is fixing. Will Tidyquant need a patch to this dependency?

**Comment by mlozanoqf** [comment]
I added the following according to Joshua Ulrich:

`install.packages("quantmod")`
`library(quantmod)`
`remotes::install_github("joshuaulrich/xts", force = TRUE)`
`remotes::install_github("joshuaulrich/quantmod@358-getsymbols-new.session")`

Then reset my session and now `tq_get()` works fine. I did not know `tidyquant` and `quantmod` were kind of related. I prefer `tidyquant`.

**Comment by Knxd3** [comment]
tq_get does not work with large number of tickers but getSymbols from Quantmod works I believe because it adds 1 second pause between requests.

x = 'GOOG', get = 'stock.prices': Error in getSymbols.yahoo(Symbols = "GOOG", env = <environment>, verbose = FALSE, : Unable to import �GOOG�.
GOOG download failed after two attempts. Error message:
HTTP error 401.

**Comment by mdancho84** [comment]
You guys just need to upgrade quantmod to the patch that fixes this issue. 

``` r
remotes::install_github("joshuaulrich/quantmod@358-getsymbols-new.session")
```

**Comment by mdancho84** [comment]
And FYI - tidyquant use's quantmod so if quantmod works, then tidyquant works.

**Comment by mdancho84** [comment]
This is fixed. 

``` r 
remotes::install_github("joshuaulrich/quantmod@358-getsymbols-new.session")

```

**Comment by mdancho84** [comment]
CRAN has `quantmod` version 0.4.20, which fixes the issue. Simply update `quantmod` if this issue affects you./
