### ISSUE TITLE
tq_index("SP500") Not Working Ubuntu

### ISSUE THREAD

**Issue by eweiss99** [business-science/tidyquant#217]
It works on my Mac, but under Ubuntu it fails. I'm using RStudio.

My code is:
**tq_index("SP500")**

And the output is:
_Getting holdings for SP500
A tibble: 0 x 0
Warning message:
In tq_index("SP500") : Error at SP500 during download. 
Error in curl::curl_fetch_disk(url, x$path, handle = handle): Could not resolve host: www.ssga.com__

**Comment by obarisk** [comment]
Could you try ping to www.ssga.com from the ubuntu?
Looks like the machine can't resolv www.ssga.com

**Comment by mdancho84** [comment]
I could not replicate. The tests seem to work on ubuntu. Not sure if you fixed this or not. Closing but can reopen if not fixed.
