### ISSUE TITLE
tq_get does not work 

### ISSUE THREAD

**Issue by tomhoel** [business-science/tidyquant#218]
`tq_get("TSLA", get = "stock.prices", complete_cases = TRUE)
`

Yielding
```
[1] NA
Warning message:
x = 'TSLA', get = 'stock.prices': Error in new.session(): Could not establish session after 5 attempts.
```

I have successfully used tidyquant before, but it has been malfunctioning for me as of late.

**Comment by mdancho84** [comment]
What version of quantmod are you running? 

99% chance that you just need to
Update your R packages.

**Comment by tomhoel** [comment]
Yes, how embarrassing. I was on 1.0.3, updated to 1.04 and everything is working fine!  
Thank you.

**Comment by mdancho84** [comment]
Ah great!! No worries.
