### ISSUE TITLE
Typo: periodReturns should not have an "s" at end

### ISSUE THREAD

**Issue by bbrewington** [business-science/tidyquant#225]
https://github.com/business-science/tidyquant/blob/a1d9b836b0f040cd86cd3b627ddea701b8a91bcf/vignettes/TQ03-scaling-and-modeling-with-tidyquant.Rmd#L125

Also, the image linked here has the "s" at the end:

https://github.com/business-science/tidyquant/blob/baf2eebbdac9bb931bfb5c0c05e9c93191c569f6/vignettes/TQ05-performance-analysis-with-tidyquant.Rmd#L128

**Comment by mdancho84** [comment]
Thanks!
