### ISSUE TITLE
List of all stock symbols for tq_get(x, get = "stock.prices")

### ISSUE THREAD

**Issue by CyGei** [business-science/tidyquant#227]
Is there a way to obtain a list of all stock symbols that the function tq_get(x, get = "stock.prices") can take?

In the documentation for: tq_get(x, get = "stock.prices") it says that `get = "stock.prices"` retrieves data for a stock symbol (`x`) from [Yahoo Finance](https://finance.yahoo.com/). Where can I get the list of all stock symbols available from Yahoo finance.

Currently, tq_index() only provides all stock symbols for a given a stock index.

**Comment by mdancho84** [comment]
Not to my knowledge. We include `tq_index` and `tq_exchange` for discovery.
