### ISSUE TITLE
Tidyquant is not available at CRAN

### ISSUE THREAD

**Issue by jmagomez** [business-science/tidyquant#230]
Dear Fellows,

I am trying to install tidyquant, but this R package is not available at CRAN. Is there any other alternative to install tidyquant?

Best Regards, José.

**Comment by mdancho84** [comment]
Working on getting `tidyquant` back asap. Here is the dependency list, which we are working on. 

- [x] timetk - needs to get back on cran
- [ ] alphavantager - needs to get back on cran
- [ ] tidyquant - needs to get back on cran

**Comment by mdancho84** [comment]
`alphavantager` is back. Will be submitting `tidyquant` shortly.
