### ISSUE TITLE
group_by(symbol) for  tq_portfolio() to calc wealth index

### ISSUE THREAD

**Issue by robby81** [business-science/tidyquant#29]
I wanted to calculate the development of a 10000 Dollor for multiple markets to compare it finally with my portfolio. I am currently trying this:

```
#get sector prices
from <- today() - years(10)
sector_prices <- ticker %>% tq_get(get = "stock.prices", from = from, to = today())
sector_monthly_returns <- sector_prices %>% group_by(symbol) %>% tq_transmute(select=adjusted, periodReturn, period = "monthly", col_rename = "Rb") %>% ungroup()

sector_growth_monthly <-  sector_monthly_returns %>% group_by(symbol) %>%
    tq_portfolio(assets_col   = symbol, 
                 returns_col  = Rb, 
                 weights      = 1, 
                 col_rename   = "investment.growth",
                 wealth.index = TRUE) %>%
    mutate(investment.growth = investment.growth * 10000, symbol = rep(symbol, n()))
```

But that does not work. Do you know of the correct way to do that?

**Comment by mdancho84** [comment]
@robby81 Davis and I are looking into this. The weights would typically be `NULL` if you wanted an equal weight portfolio. However, I think there may be a bug. We will provide a solution shortly. Thanks for you patience.

**Comment by robby81** [comment]
I came up with a solution by myself:

`# List of tickers for sector etfs. 
ticker <- c("RXI", "KXI", "IXC", "IXG", "IXJ",   
            "EXI", "MXI", "IXN", "JXI", "IXP", "HAP", "RWO")
# And the accompanying sector names for those ETFs.
sector <- c("zyklische Konsumgüter", "nichtzyklische Konsumgüter", 
            "Energie", "Finanzwesen", "Gesundheit", "Industrie", 
            "Materialien", "Technologie", "Versorger", "Telekommunikation", "Rohstoffunternehmen", "Immobilien")
etf_ticker_sector <- tibble(ticker, sector)

#get sector prices
from <- today() - years(10)
sector_prices <- ticker %>% tq_get(get = "stock.prices", from = from, to = today())
sector_monthly_returns <- sector_prices %>% group_by(symbol) %>% tq_transmute(select=adjusted, periodReturn, period = "monthly", col_rename = "Rb") %>% ungroup()

sector_growth <- sector_monthly_returns %>% group_by(symbol) %>% do(tq_portfolio(data=., assets_col   = symbol, 
                 returns_col  = Rb, 
                 weights      = 1, 
                 col_rename   = "investment.growth",
                 wealth.index = TRUE))%>%
    mutate(investment.growth = investment.growth * 10000)
sector_growth <- sector_growth %>% left_join(etf_ticker_sector, by = c("symbol" = "ticker"))
`

**Comment by DavisVaughan** [comment]
@robby81, if that solution is what you want, then that's great! But it seems like that solution calculates the wealth index for each ticker individually. If you really wanted an equally weighted portfolio, then you should do this for now. The current fix is manually setting the equal weights. The warning shown comes from HAP and RWO not having data for 2007/2008, and it just fills those return values with 0.

As Matt said, we will get a fix out shortly for the default equally weighted portfolio.

``` r
# tidyquant
suppressPackageStartupMessages(library(tidyquant))

# List of tickers for sector etfs. 
ticker <- c("RXI", "KXI", "IXC", "IXG", "IXJ",   
            "EXI", "MXI", "IXN", "JXI", "IXP", "HAP", "RWO")

# And the accompanying sector names for those ETFs.
sector <- c("zyklische Konsumgüter", "nichtzyklische Konsumgüter", 
            "Energie", "Finanzwesen", "Gesundheit", "Industrie", 
            "Materialien", "Technologie", "Versorger", "Telekommunikation", "Rohstoffunternehmen", "Immobilien")

# Bind them together
etf_ticker_sector <- tibble(ticker, sector)

# Get sector prices
from <- today() - years(10)
sector_prices <- ticker %>% 
  tq_get(get = "stock.prices", from = from, to = today())

# Monthly returns
sector_monthly_returns <- sector_prices %>% 
  group_by(symbol) %>% 
  tq_transmute(select=adjusted, periodReturn, period = "monthly", col_rename = "Rb")

# Manually set equal weights for the moment
n <- length(ticker)
weights <- rep(1/n, n)

# Portfolio returns as wealth index
portfolio_growth <- sector_monthly_returns %>% 
  tq_portfolio(assets_col   = symbol, 
               returns_col  = Rb, 
               weights      = weights, 
               col_rename   = "investment.growth",
               wealth.index = TRUE) %>%
  mutate(investment.growth = investment.growth * 10000)
#> Warning in PerformanceAnalytics::Return.portfolio(., weights = weights, :
#> NA's detected: filling NA's with zeros

# No need for this since you have portfolio growth
# sector_growth <- sector_growth %>% 
#   left_join(etf_ticker_sector, 
#             by = c("symbol" = "ticker"))
```

**Comment by robby81** [comment]
Indeed, I wanted to to calculate the wealth index for each ticker individually in order to compare them with "my" portfolio of ETF's. If you know a simpler way to do that, please let me know.

**Comment by robby81** [comment]
I am still at a starting point with doing financial analyses using R and I am not a finance expert either

**Comment by DavisVaughan** [comment]
@robby81, now I see what you are trying to do. The wealth index for each stock is really just the cumulative product of (1+return). Try this! (Note that you don't have to use `ungroup()` after calculating the monthly returns like you had done.)

``` r
# tidyquant
suppressPackageStartupMessages(library(tidyquant))

# List of tickers for sector etfs. 
ticker <- c("RXI", "KXI", "IXC", "IXG", "IXJ",   
            "EXI", "MXI", "IXN", "JXI", "IXP", "HAP", "RWO")

# And the accompanying sector names for those ETFs.
sector <- c("zyklische Konsumgüter", "nichtzyklische Konsumgüter", 
            "Energie", "Finanzwesen", "Gesundheit", "Industrie", 
            "Materialien", "Technologie", "Versorger", "Telekommunikation", "Rohstoffunternehmen", "Immobilien")

# Bind them together
etf_ticker_sector <- tibble(ticker, sector)

# Get sector prices
from <- today() - years(10)
sector_prices <- ticker %>% 
    tq_get(get = "stock.prices", from = from, to = today())

# Monthly returns
sector_monthly_returns <- sector_prices %>% 
    group_by(symbol) %>% 
    tq_transmute(select=adjusted, periodReturn, period = "monthly", col_rename = "Rb")

# Wealth index - cumulative product of (1+return)
sector_monthly_returns %>%
    mutate(wealth_index = cumprod(Rb+1) * 10000) %>%
    arrange(symbol)
#> Source: local data frame [1,420 x 4]
#> Groups: symbol [12]
#> 
#>    symbol       date           Rb wealth_index
#>     <chr>     <date>        <dbl>        <dbl>
#> 1     EXI 2007-04-30  0.036244136    10362.441
#> 2     EXI 2007-05-31  0.042134309    10799.056
#> 3     EXI 2007-06-29  0.003746576    10839.515
#> 4     EXI 2007-07-31  0.006687401    10912.003
#> 5     EXI 2007-08-31 -0.010968729    10792.313
#> 6     EXI 2007-09-28  0.044986015    11277.816
#> 7     EXI 2007-10-31  0.021225686    11517.195
#> 8     EXI 2007-11-30 -0.041861837    11035.064
#> 9     EXI 2007-12-31 -0.026839976    10738.883
#> 10    EXI 2008-01-31 -0.082122558     9856.979
#> # ... with 1,410 more rows
```

**Comment by robby81** [comment]
It was really so easy :-). Had that in mind, but was not quite sure, that it was correct. Thank you for your help!

**Comment by DavisVaughan** [comment]
I have also just fixed the `weights = NULL` problem [here](https://github.com/business-science/tidyquant/commit/84c9340e86e7a2520b4662bfc3e530dc60ebda9b). The default equal weighting scheme now works with `tq_portfolio()`. It was not the problem you were asking about, but that issue came up while solving your problem.
