### ISSUE TITLE
Why can't you finance guys also think of others?

### ISSUE THREAD

**Issue by codingbutstillalive** [business-science/tidyquant#30]
I read about your package on R-bloggers, and liked the idea of harmonizing xts with the tidyverse. But I hate that you always think of time series values to come in OHLC format.

There are millions of other data in univariate or multivariate time series format. Why do you require this damn OHLC format!?

**Comment by mdancho84** [comment]
In v0.5.0 released early this week we deprecated `ohlc_fun` for the more relevant and "tidyverse"-like `select` argument. Most of the underlying `xts`, `quantmod`, `TTR`, and `PerformanceAnalytics` functions do not require OHLC format so you should be freed from OHLC handcuffs. The blog post here explains http://www.business-science.io/code-tools/2017/04/04/tidyquant-0-5-0.html. Check out the `rollapply` example. It's worth its weight in gold.

**Comment by DavisVaughan** [comment]
@codingbutstillalive, as Matt mentioned, we don't! The newest blog post explains it well. Why restrict ourselves to OHLC data when there is so much else out there? Here's an example if you don't want to read the whole thing.

``` r
# Load tidyquant
suppressPackageStartupMessages(library(tidyquant))

# Grab some non-OHLC data
oil_prices <- tq_get("DCOILWTICO", get = "economic.data")

# Hey this works great with select!
tq_mutate(oil_prices, select = price, mutate_fun = lag.xts, k = 1) %>%
  head(3)
#> # A tibble: 3 × 3
#>         date price lag.xts
#>       <date> <dbl>   <dbl>
#> 1 2007-01-01    NA      NA
#> 2 2007-01-02 60.77      NA
#> 3 2007-01-03 58.31   60.77

# This does too! 
filter(oil_prices, !is.na(price)) %>%
  tq_transmute(select = price, mutate_fun = weeklyReturn) %>%
  head(3)
#> # A tibble: 3 × 2
#>         date weekly.returns
#>       <date>          <dbl>
#> 1 2007-01-05    -0.07372059
#> 2 2007-01-12    -0.05915793
#> 3 2007-01-19    -0.01850453
```

**Comment by codingbutstillalive** [comment]
Alright, glad to hear that you changed that. I will give it a try then. Momentarily, R is lacking some powerful general purpose time series packages. Especially, when it comes to interactive plots (except from the dygraphs package).

**Comment by mdancho84** [comment]
We'll look into the interactive plots as well. Also, time series in general is really of interest to us. Let us know if you see anything that needs fixed in tidyquant or otherwise.
