### ISSUE TITLE
marketvolume.com no longer working with tq_index()?

### ISSUE THREAD

**Issue by mrhellmann** [business-science/tidyquant#36]
tq_index() doesn't seem to be able to retrieve market components from marketvolume.com any longer.

Visited the website (https://www.marketvolume.com/indexes_exchanges/sp500_components.asp?s=SPX&row=1) for the first time, and noticed there is a popup.  Has this caused a problem with getting information from them? 

I'll stick to using `use_fallback = T` for now.

example:

    tq_index('SP500')
    Getting data...
    
    [1] NA
    Warning message:
    In value[[3L]](cond) :
      Could not access http://www.marketvolume.com/indexes_exchanges/sp500_components.asp?s=SPX&row=0. If problem persists, try setting `use_fallback = TRUE` to return the last dowloaded data set.

Thanks for a great package.

**Comment by mdancho84** [comment]
That is odd. I just checked, and it seems to be working fine for me:

```
> tq_index("SP500")
Getting data...

# A tibble: 502 × 2
   symbol                   company
    <chr>                     <chr>
1     MMM                        3M
2     ABT       ABBOTT LABORATORIES
3    ABBV                ABBVIE INC
4     ACN                 ACCENTURE
5    ATVI       ACTIVISION BLIZZARD
6     AYI             ACUITY BRANDS
7    ADBE             ADOBE SYSTEMS
8     AAP        ADVANCE AUTO PARTS
9     AET                     AETNA
10    AMG AFFILIATED MANAGERS GROUP
# ... with 492 more rows
```

**Comment by mrhellmann** [comment]
Looks like it's just a problem on my Windows computer, works fine under Ubuntu.  

Must be something on my end.

**Comment by mdancho84** [comment]
Let me know what you figure out. Windows is a pain (I also have a windows-based machine, and I'm strongly considering switching to mac for reasons like this).

**Comment by mrhellmann** [comment]
Updated to R 3.4 from 3.3  That solved the problem.  

Thanks for the quick response & keep up the good work.

**Comment by mdancho84** [comment]
Ok, great to know! Will do. Look for more to come.
