### ISSUE TITLE
Quandl URL changed from *datatables* to *datasets*

### ISSUE THREAD

**Issue by AndreMikulec** [business-science/tidyquant#52]
When I execute this, I get the following error back.
```r
tq_vix <- tidyquant::tq_get("CBOE/VIX", get  = "quandl.datatable")
```
Error
```
Warning message:
x = 'CBOE/VIX', get = 'quandl.datatable': Error: {"quandl_error":{"code":"QECx02","message":"The following datatable 'CBOE/VIX' does not exist."}}
 
```
Seen closer in this.   Little data (only 97 bytes are returned).
```r
debug: quandl.api.handl_errors(response)
Browse[3]> str(response)
List of 10
$ url        : chr "https://www.quandl.com/api/v3/datatables/CBOE/VIX?"
$ status_code: int 404
$ content    : raw [1:97] 7b 22 71 75 ...
```
When I do this
```r
q_vix <- Quandl::Quandl("CBOE/VIX")
```
I get the following response back ( with a data.frame of data ( that is not shown here ) )
```
debug: quandl.api.handl_errors(response)
List of 10
 $ url        : chr "https://www.quandl.com/api/v3/datasets/CBOE/VIX?transform=&collapse=&order=desc"
 $ status_code: int 200
```
Then I change the tidyquant R code  'on the fly'
```r
Browse[4]> debug(Quandl.datatable)

  path <- paste0("datatables/", code)
  TO
  path <- paste0("datatasets/", code)

```
And the response is good and the payload is now full.
```r
Browse[4]> str(response)
List of 10
 $ url        : chr "https://www.quandl.com/api/v3/datasets/CBOE/VIX?"
 $ status_code: int 200
 $ content    : raw [1:131774] 7b 22 64 61 ...
```
--
Then I continue(c).
But then 
```r
> str(tq_vix, list.len = 999)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	0 obs. of  0 variables
```
So the output format may be different than before??

**Comment by mdancho84** [comment]
Quandl has a unique specification for how they divide up time series and non-time series data. The data sets are time series data, and the data tables are non-time series. In `tidyquant`, the time series data (data sets) are the default `get = "quandl"), and you can access the [CBOE](https://www.quandl.com/data/CBOE-Chicago-Board-Options-Exchange) VIX data set as follows:
```
tidyquant::tq_get("CBOE/VIX", get = "quandl")
```

The non-time series data (data tables) are for data such as [Mergent Global Fundamentals Data](https://www.quandl.com/databases/MF1?filterSelection=all&keyword=MER)

```
tidyquant::tq_get("MER/F1", get = "quandl.datatable")
```

**Comment by AndreMikulec** [comment]
Thanks.

**Comment by mdancho84** [comment]
You're welcome! Let us know if you come across anything else.
