### ISSUE TITLE
install error on rstudio

### ISSUE THREAD

**Issue by jasonajones73** [business-science/tidyquant#54]
Error when installing in RStudio, either through install.packages("tidyquant") or devtools::install_github("business-science/tidyquant"). 

Opened independent session of R and it installed on first try and then was available to load when I opened RStudio again.

**Comment by mdancho84** [comment]
I just tried both install.packages() and install_github() and bot seemed to work. 

Sometimes RStudio gives me trouble if I've been in it for a while and then try to install. Usually when I close and reopen, it works fine. Might be the case here.
