### ISSUE TITLE
Add Google Finance Data Source: diversify data sources (enhancement)

### ISSUE THREAD

**Issue by helgasoft** [business-science/tidyquant#63]
Library tidyquant is quite useful, but is hard-coded to Yahoo stock price data (see '_stockprice_' in _tq_get_util_1_).  Lately Yahoo stock price data has become somewhat unreliable.
A good enhancement would be to add Google as alternative data source, **getSymbols.google** is already available in _quantmod_, it would be just a matter of including it in code.

**Comment by mdancho84** [comment]
We agree. We are also adding alphavantager as well because of the yahoo debacle. Reliability is extremely important.

**Comment by mdancho84** [comment]
@helgasoft I've integrated getSymbols.google. Use `tq_get(get = "stock.prices.google") and it should return data from Google Finance.
