### ISSUE TITLE
Unable to load key.ratios data from outside the US

### ISSUE THREAD

**Issue by moraesmark** [business-science/tidyquant#69]
Dear Matt,

I'm attempting to retrieve key ratio information for public companies located in India through the morningstar wrapper. However, I get a 'NA' return. I plugged in the company codes into the morningstar Url to retrieve the key.ratios page, and it worked on the browser. So I'm not sure, what could be the issue preventing the wrapper for returning the data.

Data <- tq_get(c("SUNPHARMA", "APOLLOHOSP"), get = "key.ratios")

Regards,

Mark

Edit: I just noticed, there are active open issues attempting to find a solution for the same problem. So may I request this issue be referenced to the other issues open and then closed.

Cheers

**Comment by mdancho84** [comment]
Yes, this is something that will be addressed soon. It's an issue with pull data from two sources. Sometimes the symbols are different and/or not available in both sources which causes this issue. We will address.
