### ISSUE TITLE
tq_get seems to be pulling incorrect data

### ISSUE THREAD

**Issue by renrele** [business-science/tidyquant#79]
stocks <- tq_get("QQQ", get = "stock.prices", complete_cases = TRUE, from="2001-12-27", to="2017-11-15")
> head(stocks)
# A tibble: 6 x 7
        date   open   high    low close   volume adjusted
      <date>  <dbl>  <dbl>  <dbl> <dbl>    <dbl>    <dbl>
1 2001-12-27 44.682 45.075 44.402 40.01 34255200 35.68291
2 2001-12-28 45.176 45.748 45.108 40.33 38240400 35.96831
3 2001-12-31 45.198 45.355 43.628 38.91 46176900 34.70188
4 2002-01-02 44.368 45.019 43.651 40.11 61708800 35.77210
5 2002-01-03 45.198 46.589 45.142 41.50 85769100 37.01177
6 2002-01-04 47.037 47.418 45.893 41.67 86876900 37.16337

As you can see the low data is greater than the close!  When I got the same data directly from Yahoo Finance I got completely different values for OHL, but the close is identical

Date | Open | High | Low | Close
-- | -- | -- | -- | --
  |   |   |   |  
27/12/2001 | 39.85 | 40.2 | 39.6 | 40.01
28/12/2001 | 40.29 | 40.8 | 40.23 | 40.33
31/12/2001 | 40.31 | 40.45 | 38.91 | 38.91
02/01/2002 | 39.57 | 40.15 | 38.93 | 40.11
03/01/2002 | 40.31 | 41.55 | 40.26 | 41.5
04/01/2002 | 41.95 | 42.29 | 40.93 | 41.67

These values seem to be correct. So what is going wrong with tq_get???

**Comment by mdancho84** [comment]
That's weird. When I run the call here is what I get. It seems to match your Yahoo Finance web result in the table you provided.

```
> tidyquant::tq_get("QQQ", get = "stock.prices", complete_cases = TRUE, from="2001-12-27", to="2017-11-15")

# A tibble: 4,000 x 7
         date  open  high   low close   volume adjusted
       <date> <dbl> <dbl> <dbl> <dbl>    <dbl>    <dbl>
 1 2001-12-27 39.85 40.20 39.60 40.01 34255200 35.68291
 2 2001-12-28 40.29 40.80 40.23 40.33 38240400 35.96831
 3 2001-12-31 40.31 40.45 38.91 38.91 46176900 34.70188
 4 2002-01-02 39.57 40.15 38.93 40.11 61708800 35.77210
 5 2002-01-03 40.31 41.55 40.26 41.50 85769100 37.01177
 6 2002-01-04 41.95 42.29 40.93 41.67 86876900 37.16337
 7 2002-01-07 42.11 42.22 40.11 41.21 75166200 36.75312
 8 2002-01-08 41.10 41.77 40.84 41.49 66956800 37.00285
 9 2002-01-09 42.04 42.60 40.90 41.11 85123000 36.66395
10 2002-01-10 41.17 41.54 40.68 41.38 75548000 36.90475
# ... with 3,990 more rows
```

**Comment by renrele** [comment]
I agree - it is very weird! I can't understand why this is happening. Not
just for this stock - for everything! I cant get the correct data. ah - and
it's not just today. It happens every time I try to use tq_get

2017-11-20 15:59 GMT+02:00 Matt Dancho <notifications@github.com>:

**Comment by mdancho84** [comment]
Really? That is very odd. What about when you use `quantmod`? Same issue?

**Comment by renrele** [comment]
Yes - same again.  :(
 getSymbols("QQQ",src = "yahoo",from = as.Date("2001-12-27"), to = as.Date("2002-01-10"))
[1] "QQQ"
> head(QQQ)
           QQQ.Open QQQ.High QQQ.Low QQQ.Close QQQ.Volume QQQ.Adjusted
2001-12-27   44.682   45.075  44.402     40.01   34255200     35.68291
2001-12-28   45.176   45.748  45.108     40.33   38240400     35.96831

2001-12-31   45.198   45.355  43.628     38.91   46176900     34.70188
2002-01-02   44.368   45.019  43.651     40.11   61708800     35.77210
2002-01-03   45.198   46.589  45.142     41.50   85769100     37.01177
2002-01-04   47.037   47.418  45.893     41.67   86876900     37.16337

**Comment by DavisVaughan** [comment]
What version of quantmod do you have? Try `install.packages("quandmod")`. Might be an issue that was fixed by them.

**Comment by renrele** [comment]
Bingo!
I reinstalled both tidyquant and quantmod and now they both work. Thank you so much!!

**Comment by mdancho84** [comment]
Alright. Sounds great. Glad you figured it out. I'm closing this out.
