### ISSUE TITLE
I am getting a HTTP error 400 on tq_get() from Yahoo

### ISSUE THREAD

**Issue by sunnyc7** [business-science/tidyquant#81]
Error:
```
tq_get("AAPL")
[1] NA
Warning message:
x = 'AAPL', get = 'stock.prices': Error: AAPL download failed after two attempts. Error message:
HTTP error 400.
```
Also, when I try to use Quandl, I am getting an API Error.
```
R> tq_get(tick, get = "quandl", from = from)
[1] NA
Warning message:
x = 'AAPL', get = 'quandl': Error: {"quandl_error":{"code":"QECx05","message":"The url you requested is incorrect. Please use the following url instead: /api/v3/datasets/:database_code/:dataset_code."}}
```
my Options:
```
R> tq_get_options()
[1] "stock.prices"       "stock.prices.japan" "financials"         "key.stats"          "key.ratios"         "dividends"     [7] "splits"             "economic.data"      "exchange.rates"     "metal.prices"       "quandl"             "quandl.datatable"  
```

Did something break with the tq API ?

**Comment by sunnyc7** [comment]
QuantMod Yahoo downloader is broken. 
https://github.com/joshuaulrich/quantmod/issues/202

**Comment by mdancho84** [comment]
Yeah, this looks like more Yahoo fun! Yahoo is terrible. 

As a workaround please install the development version using `devtools::install_github("business-science/tidyquant")` and use `tq_get("AAPL", get = "stock.prices.google")` 

or

 `tq_get("AAPL", get = "alphavanteger")` with the API key setup first (`av_api_key()`).

**Comment by sunnyc7** [comment]
@mdancho84  Thanks for that 👍 
This works

```
devtools::install_github("business-science/tidyquant") 
library("tidyquant")
tq_get("AAPL", get = "stock.prices.google")


```

**Comment by mdancho84** [comment]
Yahoo seems to be working now.

**Comment by sunnyc7** [comment]
Would it be a good idea to see if the API is working before calling tq_get() ?
