### ISSUE TITLE
Failure to install tidyquant from master due to a dependency resolution problem 

### ISSUE THREAD

**Issue by szaydel** [business-science/tidyquant#86]
I observed this today when attempting to add `tidyquant` package to my Anaconda-based jupyter-notebook Docker instance.

There's no reason to believe that this is specific to Docker or Anaconda as the base platform, but I am happy to chase those possibilities to help address this.

```
ERROR: dependency ‘alphavantager’ is not available for package ‘tidyquant’
* removing ‘/opt/conda/lib/R/library/tidyquant’
Installation failed: Command failed (1)
```

Thanks!

**Comment by mdancho84** [comment]
It seems from the error comment that `alphavantager` is not being installed. I'd try installing with devtools. 
```
devtools::install_github("business-science/alphavantager")
devtools::install_github("business-science/tidyquant")
```

**Comment by szaydel** [comment]
I would have thought that this would be listed as a pre-req., and I actually just noticed that it requires version of R later than what is shipped with this version of docker container. So I am going to see if this is even going to be possible. Should this package not be handled as part of the install of `tidyquant` though?

Thanks a lot for a rapid reply! 👍

**Comment by mdancho84** [comment]
It should, and I'm unsure why it's not loading. Just trying to give you a possible solution.

**Comment by szaydel** [comment]
Thank you Matt. Yeah, I was less after a solution, which I know I could come-up with and more about logging a possible friction point someone else might experience when they attempt to load and use this package. Having said that I did not test from CRAN, which likely is where most people are getting their installation package. I was able to update the Conda distribution and install `alphavantager` package separately. Thanks again!

**Comment by szaydel** [comment]
So the version problem may be root cause for what I experienced. At least that's my best guess right now.
```
'/opt/conda/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/tmp/RtmpWP94Fs/devtools179c7b8abe01/business-science-alphavantager-1f72adf'  \
  --library='/opt/conda/lib/R/library' --install-tests

ERROR: this R is version 3.3.2, package 'alphavantager' requires R >=  3.4.0
Installation failed: Command failed (1)
>
```

I think it is safe to close this, though I will see if I have issues with later version of R, and if you'd like to keep this open, we can and I will report my observations.

Thanks!

**Comment by mdancho84** [comment]
OK, glad to see that you were able to get it working. We can reopen it if the issue persists.

**Comment by szaydel** [comment]
Thank you Matt.
