### ISSUE TITLE
Reliance on alphavantager/install problems

### ISSUE THREAD

**Issue by RinSydney** [business-science/tidyquant#94]
Tidyquant is failing to install on a corporate R installation due to the requirement to include alphavantager which is only compatible with R 3.3.4 and above (corporate restrictions mean latest version of R is not yet approved).

**Comment by DavisVaughan** [comment]
I've reduced the `alphavantager` requirement to R 3.3.0, and `tidyquant` now only Suggests the use of `alphavantager` rather than requires it. If you can do `devtools::install_github("business-science/tidyquant")` you should be able to access it.

**Comment by RinSydney** [comment]
Tested and that now works perfectly - many thanks for making the change.
