### ISSUE TITLE
subtle change in tq_get for downloading stock.prices

### ISSUE THREAD

**Issue by nitingupta2** [business-science/tidyquant#98]
Hi,

I noticed a subtle change in tq_get functionality as regards to downloading stock.prices data.
In the earlier versions of tidyquant, both **from** and **to** dates were included in the download. Perhaps recently this has been changed to exclude the **to** date to download only the data prior to the **to** date. Could you confirm this was an intended change?

Thank you.

**Comment by mdancho84** [comment]
I'm not sure what change you are referring to. We have not changed anything related to from/to logic.

**Comment by nitingupta2** [comment]
Thanks Matt. Seems like this change was made downstream in the quantmod package.
Here's an example:

```
> df1 <- tq_get("SPY", get = "stock.prices", from = "2018-03-26", to = "2018-03-30")
> df1
# A tibble: 4 x 7
  date        open  high   low close     volume adjusted
  <date>     <dbl> <dbl> <dbl> <dbl>      <dbl>    <dbl>
1 2018-03-26  262.  265.  259.  265. 141956100.     265.
2 2018-03-27  266.  267.  259.  261. 129941400.     261.
3 2018-03-28  261.  263.  259.  260. 146452300.     260.
4 2018-03-29  261.  265.  260.  263. 111601600.     263.

> df2 <- quantmod::getSymbols("SPY", auto.assign = F, from = "2018-03-26", to = "2018-03-30")
> df2
           SPY.Open SPY.High SPY.Low SPY.Close SPY.Volume SPY.Adjusted
2018-03-26   262.13   265.43  259.41    265.11  141956100       265.11
2018-03-27   266.17   266.77  258.84    260.60  129941400       260.60
2018-03-28   260.75   262.64  258.58    259.83  146452300       259.83
2018-03-29   261.12   265.26  259.84    263.15  111601600       263.15

> df3 <- quantmod::getSymbols("SPY", auto.assign = F, from = "2018-03-26", to = "2018-03-29")
> df3
           SPY.Open SPY.High SPY.Low SPY.Close SPY.Volume SPY.Adjusted
2018-03-26   262.13   265.43  259.41    265.11  141956100       265.11
2018-03-27   266.17   266.77  258.84    260.60  129941400       260.60
2018-03-28   260.75   262.64  258.58    259.83  146452300       259.83
```

**Comment by mdancho84** [comment]
Oh, I know what this is. It's the `tibble` print formatting. The actual values are the same. Just the way `tibbles` now get printed in a condensed format. It's been throwing some people off when viewing, but the actual values are 100% the same.

**Comment by nitingupta2** [comment]
Formatting isn't the issue here. I was trying to bring your attention to the dates. Note the 'from' and 'to' dates requested. Data for the 'to' date isn't included in the download any more. Earlier, data for both 'from' and 'to' dates was included in the downloaded set. I can't pinpoint when this change has happened.

**Comment by mdancho84** [comment]
Closing issue - looks like this has been resolved.
